### ISSUE TITLE
#12 Update Activity Details with About Activity, Experience ( e.g.  Important Information, etc. ...)  ✅

### ISSUE THREAD

**Issue by RebeccaDrm** [akopp90/activity-planner#17]
## Value proposition
As a user
I want to see further information about the activity. 
In order to see the  the duration and the size of the group.
Furthermore I want to see more information about the whole experience, like the full description (program), what is included, not suitable for..., what to bring, what is not allowed, know before you go.

## Description
![Image](https://github.com/user-attachments/assets/271c325c-d75b-4aae-9508-bfd06d4ec948)

## Acceptance criteria
- [ ] the detailspage displays a section "About this activity" under the description
- [ ] "About this activity" should have a list with this information:

- duration
- size of the group 

- [ ] Each item should have an icon, a title and a short information.
- [ ] Under the "About this activity" display a headline "About this Experience".
- [ ] "About this Experience" should have a list with this information:

- full description
- not suitable for...
- what to bring
- what is not allowed
- know before you go

## Tasks
- [ ] Create feature branch `feature/activity-details-extras`
- [ ] Update the existing activities.js with the further information above.
- [ ] Update the ActivityForm.js with the new Input fields.
- [ ] Update the ActivityDetails.js to show the new information.

**Comment by Roland-Hufnagel** [comment]
Hey team, there are a few points I want to mention: 
- Please write the AC as a description of the correct working User Interface. Instead of 'add a section' (what is a task) you can write 'the detailspage displays a section under the description'.
- In your wireframe some 'about this activity' list items look like buttons with functionallity (Check availability, reserve now...). Please keep in mind: You always have to present a working app. There should be no placeholders like buttons without functionallity. So you might either reduce the userstory or add the missing tasks. (Of cause you can begin with e.g. one functionallity and add more in the future)

**Comment by predrag-babic** [comment]
Hi Team,
as Rolad mentioned, your AC is more like a task:
![Image](https://github.com/user-attachments/assets/23f8d3ab-15f1-44ad-9b2a-b5eb518ee03d)
Maybe you should change it in "displayed" and not add a section.
