### ISSUE TITLE
#3 Activity Details

### ISSUE THREAD

**Issue by akopp90** [akopp90/activity-planner#2]
## Value Proposition

**As a user,**

**I want to** access detailed information about each activity,

**so that** I can make informed decisions and plan my activities effectively.

## Description

Capstone Group Todo: ![wireframe](https://raw.githubusercontent.com/akopp90/activity-planner/refs/heads/main/public/activity-details.png)

## Acceptance Criteria

- Each activity in the activities list has a link to a details page.
- Each details page contains:
  - Activity title <Link>
  - Activity image
  - Activity description
  - Activity categories
  - Activity area
  - Activity country
- The detailed view includes a "back" link, allowing users to easily navigate back to the list of activities.

## Tasks

- [ ] Create feature branch `feature/activity-details`
- [ ] Design the activity page based on the details that should be contained from acceptance criteria above
- [ ] Create an Activity Details component
- [ ] Add placeholders for all components like picture, tags, etc
- [ ] Add a back Link which navigates back to the list of activities
- [ ] Fetch the information from the database for the activity

**Comment by JessicaLoers** [comment]
As mentioned this morning it’s not entirely clear what links to the details page. 
Please improve this.   Add a wireframe that shows the user how to get from the homepage to the details page.
