### ISSUE TITLE
#14  Travel Tips / Random Travel Tips ✅

### ISSUE THREAD

**Issue by akopp90** [akopp90/activity-planner#21]
## Value proposition
As a user
I want to access a comprehensive, easy-to-read travel tips page,
So that I can prepare effectively for my trip, feel confident navigating new destinations, and avoid common travel mistakes.
## Description
![Image](https://github.com/user-attachments/assets/42a31f25-71f1-4e9f-a343-34e8c6d5b528)

## Acceptance criteria
- [ ] The landing page, includes a "Travel Tips" section with 4 button at the bottom of the page.
- [ ] When the user clicks any of the buttons (Water Sport, Adventure, Outdoor Adventure,Winter Sports), the app navigates them to a new page that shows information related to the selected category.
- [ ] These buttons are clearly labeled and easy to click, guiding the user to the relevant tips for each activity category.
- [ ] Each category page includes a Image and Informations.
- [ ] At the bottom of the page, there is a section for recommended activities based on the tips provided.
- [ ] This sections includes Activity categories and Images to click on.
## Tasks
- [ ] Create feature branch `feature/travel-tips1`
- [ ] Ensure proper navigation between the landing page and the Travel Tip pages when any of the buttons are clicked.
- [ ] Design and build individual pages for each category (Water Sport, Adventure, Outdoor Adventure,Winter Sports).
- [ ] Include a list of travel tips for each category (e.g., for Water Sports: "Check weather conditions," "Wear the right gear," etc.).
- [ ] Develop a section at the bottom of each category page displaying recommended activities based on the travel tips.
- [ ] Each activity should have an image and a link that leads to more detailed activity information.
- [ ] Ensure that recommended activities are dynamically shown based on the category the user selected.
- [ ] Ensure proper navigation between the Travel Tip pages and the Activity Details Page.

**Comment by Roland-Hufnagel** [comment]
I like this userstory. I can recommend the following:
You can add a datastructure e.g. in the lib folder like an array having obejcts for each category of travel tip. You can then render a dynamic page using this datastructure. This way you can easily add or remove things by changing the data.

This userstory is in conflict with the other Landing Page story. I recommend to remove the travel tipps from the other story and keep this one to implement the travel tipps.
