### ISSUE TITLE
#15 Search Activities ✅

### ISSUE THREAD

**Issue by akopp90** [akopp90/activity-planner#22]
## Value proposition

As a **user**
I want to **be able to search for activities**
So that **I can quickly find a specific activity without scrolling through the entire list.**

## Description
![wireframe](https://raw.githubusercontent.com/akopp90/activity-planner/refs/heads/main/public/wireframes/search-activites.png)

## Acceptance criteria
- [ ] A search bar is implemented at the top of the activities list page
- [ ] The activity list updates immediately as the user types (instant feedback)
- [ ]  If no activity matches the search term, a message is displayed to inform the user
- [ ]  The search functionality is case-insensitive to improve usability (optional but helpful)

## Tasks
- [ ] Create feature branch `feature/search-activities`
- [ ] Insert an input field at the top of the activities list page
- [ ] Handle user input with real-time updates as the user types
- [ ] Handle input toLowercase to make the search case insensitive
- [ ] Filter and update the activity list according to the search term
- [ ] Display a clear "No activities found" message if no matches are found

**Comment by Bianca-Gundel** [comment]
Looks really good, maybe descripe the optional acceptance criteria in the task. "The search functionality is case-insensitive to improve usability (optional but helpful)"
