### ISSUE TITLE
#6 Bookmark Activity

### ISSUE THREAD

**Issue by akopp90** [akopp90/activity-planner#5]
## Value Proposition

**As a user,**

**I want to** mark activities as favourites,

**so that** I can quickly access and track the ones I am most interested in.

## Description

Capstone Group Todo: ![wireframe](https://raw.githubusercontent.com/akopp90/activity-planner/refs/heads/main/public/bookmark-activity.png)

## Acceptance Criteria

- Each listed activity includes a bookmark option.
- Clicking the bookmark button of an unbookmarked activity adds it to the bookmarked list.
- Clicking the bookmark button of a bookmarked activity removes it from the bookmarked list.
- The bookmarked activities are displayed on a separate list accessible via a new page dedicated to bookmarked activities.
- There is a clearly visible link on the homepage to navigate to the bookmarked activities page.
- There is a clearly visible link on the bookmarked activities page to navigate back to the homepage.
- Bookmarked activities are visually highlighted by a distinct bookmark icon colour to differentiate them from unbookmarked activities.
- If there are no bookmarked activities in the bookmarked list, a message is displayed to the user indicating that there are no bookmarks.

## Tasks

- [ ] Create feature branch: `feature/create-bookmark` 
- [ ] Capstone Group Todo: Add tasks
- [ ] Design and add a form at the top of the homepage for creating Favourites..
- [ ] Add a headline explaining the form’s purpose (e.g., "Add a New Bookmark").
- [ ] Add all required form fields (e.g., URL, title, category).
- [ ] Handle form submission and data storage for bookmarks.
- [ ] Use `router.push` to navigate back to HOME after submission.
- [ ] Add a bookmark option to each listed activity:
- [ ] Clicking the bookmark button of an unbookmarked activity adds it to the bookmarked list.
- [ ] Clicking the bookmark button of a bookmarked activity removes it from the bookmarked list.
- [ ] Create a new page dedicated to displaying bookmarked activities.
- [ ] Include a clearly visible link on the homepage to navigate to the bookmarked activities page.
 - [ ] Add a link on the bookmarked activities page to navigate back to the homepage.
 - [ ] Visually highlight bookmarked activities with a bookmark icon to differentiate them from unbookmarked activities.
- [ ] Display a message indicating "No bookmarks available" if there are no bookmarked activities in the list.

💡 Remember, dynamic form fields can be used for accommodating multiple categories.

**Comment by JessicaLoers** [comment]
I'm not entirely clear on this tasks. What exactly are we submitting with a for the bookmark feature?

> - Handle form submission and data storage for bookmarks.
> - Use router.push to navigate back to HOME after submission.


Otherwise tip top 👍
