### ISSUE TITLE
#1 Activities List

### ISSUE THREAD

**Issue by akopp90** [akopp90/activity-planner#7]
## Value Proposition

**As a user**,

**I want to** browse a list of activities,

**so that** I can easily find and explore new activities that interest me.

## Description

Capstone Group Todo: [Wireframes](https://github.com/akopp90/activity-planner/blob/main/public/activity-list.png)

![wireeframe](https://raw.githubusercontent.com/akopp90/activity-planner/refs/heads/main/public/activity-list.png)

## Acceptance Criteria

- The homepage displays a list of activities.
- The activities list is headlined with its purpose.
- Each activity listing includes:
  - Activity title
  - Activity image
  - Activity categories
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch `feature/activities-list`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/activities.json)
  - [ ] Add an `imageUrl` for each project, for example from [unsplash.com](https://unsplash.com)
- [ ] Capstone Group Todo: Add tasks
- [ ] Create Header component
- [ ] Create ActivityList component
  - [ ] Create ActivityCard component
- [ ] Create global styling
- [ ] Style components

**Comment by JessicaLoers** [comment]
It would be nicer to have only the Wirefame image, i.e. without the list on the left and the display on the right. 
But I don't want to be so strict 😉  

US is approved ✅
